bootstrap:
  container_env_file: .env
  container_mount_path: /homelab-data
  docker_socket_path: /var/run/docker.sock
  host_data_path: /srv/homelab
general:
  image: docker.io/library/homelab:latest
  inventory_publication_group: servers-inventory
